### ISSUE TITLE
"npm run dev" never starts webpage

### ISSUE THREAD

**Issue by AnimishTemple** [cis3296s24/tth#13]
![Screenshot (48)](https://github.com/cis3296s24/tth/assets/143827597/3991fe2c-95ac-4e44-9843-e48d739632ae)

It seems like an infinite loop, I don't know why it's not starting, and the execution of the program is not ending either (might be a dumb mistake on my part)

**Comment by tun08131** [comment]
you will need to click on the local host 3000
