### ISSUE TITLE
Problems installing jnode

### ISSUE THREAD

**Issue by tun51789** [cis3296s24/tth#14]
After successfully installing the latest version of jnode, I wasn't able to run the npm run dev command, giving me the following error:

![image_2024-04-12_120657738](https://github.com/cis3296s24/tth/assets/143668310/bdc31ca0-c773-455c-80b0-c5f89e05dd6b)

Thus, I wasn't able to run the code

**Comment by tun08131** [comment]
are you in the right directory?

**Comment by tun08131** [comment]
did you do npm install?
