### ISSUE TITLE
Feed/Pictures

### ISSUE THREAD

**Issue by levinoscar** [cis3296s24/tth#35]
Hi. I was able to download for some time. While running the application. It looks really cool. Did the signup no problem and some some testings. While doing that, I was looking at the Feed section, It's showing the names and pictures that is not placed correctly on things. Like for instances I see 2 "cat" with one having an actual cat whereas another has a dog image instead. However both of those should be in the "Animals" section. I'm not saying it's bad, but I just noticed that it's not placed with where the usual feed pictures/names would be displayed in. "Assignments" should have hw and free hw, but it's not placed in there.

I would just tweak some stuff out on the Feed section and make that look clean with having the pictures/details in placed. Especially in the search bar. Nothing too crazy to work with.

Overall, the project looks pretty cool. Awesome stuff.

**Comment by tun08131** [comment]
yeah thank you for the feedback, those stuff that you mention is us messing around the app in the beginning of the testing for our app
