### ISSUE TITLE
Confirmation for contact

### ISSUE THREAD

**Issue by DeanRoos** [cis3296s24/tth#37]
Really like the layout of the site, from a UI perspective I think that some sort of confirmation before messaging the seller when clicking on the "contact" button would be helpful. 

I know the way some apps do it is by switching screens to the chat window but having the default message only typed, not sent. That way the user can customize or at least make sure they want to send this message. I really like the idea, I think this could be a legit business idea.

**Comment by tun08131** [comment]
Thank you I will take that into consideration
