### ISSUE TITLE
Update package install instructions

### ISSUE THREAD

**Issue by justinmmeans** [cis3296s24/tth#8]
Issue while attempting to build project following readme steps directly.

The current readme iteration assumes that the user has a package manager such as homebrew for macOS or chocolatey for Windows, and thus is able to download the node dependencies. For those who do already have a package manager but not node installed they will be met with a response of"command not found: npm" on macOS.

Instructions should likely include a reference to download homebrew. Installation of node via the package manager. Then the already included information in the readme.

**Comment by tun08131** [comment]
you should install node first and check if you have it, and then in the directory of tth/tth do npm install to install the node package.
