### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by MatthewChristofas** [cis3296s24/tth#9]
My laptop is an M1 Macbook Air and I was able to download the program and get it running properly. Had to do npm run dev twice to get it to open properly. Once on the site, I explored all of the tabs and pages. I created an account and also made my first post. Under the services tab at the top, the help and about pages currently show nothing. I can't filter for clothing on the feed using the options window, even though I know it's a category because that's what I listed my post under. After logging into my account and clicking the home button, the home page is still the same as it was before I logged in but I am still actually logged in. Nothing shows up under account, bought, sold items, and messaging in the Profile tab. I'm assuming these things haven't been implemented yet but I can't seem to find a buy feature anywhere or any way to message people about their listings.
<img width="653" alt="Screenshot 2024-04-11 at 5 33 34 PM" src="https://github.com/cis3296s24/tth/assets/143641850/9ce82d56-ab8b-4965-8fbb-90e3b3b77443">

**Comment by tun08131** [comment]
we were still working on that feature now is done
